### ISSUE TITLE
How to make etc

### ISSUE THREAD

**Issue by waterwin** [RPi-Distro/raspi-gpio#13]
For the not so smart, please explain what to do to install this tool on RPi4 or RPi3.

make?
make install?
sudo ./install-sh

Thanks to help me out.

**Comment by XECDesign** [comment]
I'd expect this to work:
```
./configure
make
sudo make install
```

**Comment by waterwin** [comment]
Indeed it does, source = http://inti.sourceforge.net/tutorial/libinti/autotoolsproject.html

after installing automake

$ ./configure --prefix=some_directory
$ make
$ make install
--

And thanks as well for the quick reply!

**Comment by pelwell** [comment]
A brief note on building has been added to the README.
