### ISSUE TITLE
Does raspi-gpio command also works with Raspberry Pi 4B?

### ISSUE THREAD

**Issue by hellotwozeroonethree** [RPi-Distro/raspi-gpio#16]
The command "sudo raspi-gpio help" shows the tool raspi-gpio is designed to debug BCM283X GPIO and it does not mention BCM2711 which the Raspberry Pi 4B used. Then, why is this "raspi-gpio" can be used in Raspberry pi 4B(I have checked this command on  
Raspberry Pi 4B.)
I am looking forward to receiving your reply.

Thanks very much.

**Comment by pelwell** [comment]
BCM2711 can be considered to be BCM2838, even though that name has never appeared anywhere officially.

The VideoCore family of Broadcom devices have a strange dual naming scheme, intended to differentiated between the bare die and the packaged chip (or something like that). The BCM2708 die when packaged is known as BCM2835, BCM2709 becomes BCM2836, and BCM2710 turns into BCM2837.

This pattern breaks when it gets to BCM2711, when BCM2711 is also the name of the package. We had expected it to be called BCM2838, which caused problems for us in the kernel's Device Tree support - we were using `bcm27xx-*` for our downstream versions, with upstream using `bcm283x-`, resulting in a name clash. However, that doesn't stop BCM283X being a reasonable umbrella name for the family of SoCs.
