### ISSUE TITLE
raspi-gpio command exit status is 0 when "must be root" error has been thrown

### ISSUE THREAD

**Issue by The-Mag-Pie** [RPi-Distro/raspi-gpio#20]
Example of correct exit status when error has been thrown:
![image](https://github.com/RPi-Distro/raspi-gpio/assets/90430867/6edf952c-9104-4acf-8ae9-6aba65203c70)

Example of incorrect exit status when error has been thrown (exit status is always 0):
![image](https://github.com/RPi-Distro/raspi-gpio/assets/90430867/80359e82-d682-4786-9d32-ccc23ae06027)

**Comment by pelwell** [comment]
Fixed by e6f59dc88331337fd055e7e65c0d63ecda04ac1c.
