### ISSUE TITLE
raspi-gpio command does not work on Raspberry Pi 5

### ISSUE THREAD

**Issue by uugear** [RPi-Distro/raspi-gpio#21]
I am testing with Raspberry Pi OS with Desktop (released on October 10th 2023). I found the raspi-gpio command doesn't work on Raspberry Pi 5:

```
$ raspi-gpio get
Unexpected ranges data (7c000000 00000010 7c000000)
Must be root
```

Even if running it with sudo, it still doesn't work:

```
$ sudo raspi-gpio get
Unexpected ranges data (7c000000 00000010 7c000000)
```

When I put the same SD card on my Raspberry Pi 3, the raspi-gpio command works perfectly.

**Comment by ghollingworth** [comment]
raspi-gpio is not supported on Pi 5, instead there is pinctrl

https://github.com/raspberrypi/utils
