### ISSUE TITLE
Won't set outputs on bank 1 of the compute module

### ISSUE THREAD

**Issue by samskiter** [RPi-Distro/raspi-gpio#3]
I assume this is the same tool i get by `sudo apt-get install raspi-gpio` on raspbian?

I've just spent a long time trying to debug my GPIO pins. 12/13 on bank 0 work fine as outputs. But 32,34,35,36,37&44 (all on bank1) will not work as outputs. Input behaviour works fine.

Just tried using wiringPi's gpio utility which WILL manipulate my gpio pins on bank 1.

**Comment by pelwell** [comment]
Yes, you've found the right repo, and the bug was easy to find and fix. It shouldn't take long for this to be merged and end up in a release, but until then you can download a prebuilt version [here](https://drive.google.com/file/d/0B8VsfKAD4-NOY0JobHNXNW1uNFk/view?usp=sharing).

**Comment by XECDesign** [comment]
Let me know if there are any problems with the .deb pushed to the repo a few minutes ago. Thanks.

**Comment by samskiter** [comment]
You guys are awesome. totally working - checked 34 and 44

:)
